ok

diff --git a/git-branch-status b/git-branch-status
--- a/git-branch-status
+++ b/git-branch-status
@@ -117,7 +117,9 @@ readonly INNER_PADDING_W=13 # '| ' + ' | ' + ' | ' + ' | ' + ' |'
 readonly MARGIN_PAD_W=2
 readonly MARGINS_PAD_W=$(( $MARGIN_PAD_W * 2 ))
 readonly ALL_PADDING_W=$(( $INNER_PADDING_W + $MARGINS_PAD_W ))
-readonly MIN_TTY_W=60 # ASSERT: (0 < $ALL_PADDING_W << $MIN_TTY_W)
+readonly MAX_DIVERGENCE_W=12 # e.g. "(behind 999)"
+readonly MIN_TTY_W=60 # ASSERT: (0 < ($ALL_PADDING_W + (MAX_DIVERGENCE_W * 2)) <= $MIN_TTY_W)
+readonly MARGIN_PAD=$(printf "%$(( $MARGIN_PAD_W ))s")
 readonly CWHITE='\033[0;37m'
 readonly CRED='\033[0;31m'
 readonly CGREEN='\033[0;32m'
@@ -134,6 +136,7 @@ readonly CNOLOCAL=$CRED
 readonly HRULE_CHAR='-'
 readonly JOIN_CHAR='~'
 readonly JOIN_REGEX="s/$JOIN_CHAR/ /g"
+readonly TRIM_REGEX="s/.*\(.\{$MAX_DIVERGENCE_W\}\)$/\1/"
 readonly STAR='*'
 readonly DELIM='|'
 readonly NO_UPSTREAM="(no${JOIN_CHAR}upstream)"
@@ -142,6 +145,12 @@ readonly LOCALS_SYNCED_MSG="All tracking branches are synchronized with their up
 readonly BRANCH_SYNCED_MSG="This tracking branch is synchronized with it's upstream"
 readonly UNTRACKED_SYNCHED_MSG="These branches are synchronized with no tracking relationship"
 readonly REMOTES_SYNCED_MSG="All remote branches with identically named local branches are synchronized"
+# readonly SHOW_DATES      # Init()
+# readonly SHOW_ALL_SYNCED # Init()
+# readonly SHOW_ALL_LOCAL  # Init()
+# readonly SHOW_ALL_REMOTE # Init()
+# readonly FILTER_BRANCH   # Init()
+# readonly COMPARE_BRANCH  # Init()
 
 
 ## variables ##
@@ -163,6 +172,23 @@ declare -a RemoteColors=()
 
 
 ## helpers ##
+
+function AssertIsValidRepo
+{
+  [ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" == 'true' ] || \
+  ! (( $(AssertIsNotBareRepo) ))                                      && echo 1 || echo 0
+}
+
+function AssertHasCommits
+{
+  # TODO: does this fail if detached HEAD ?
+  [ "$(git cat-file -t HEAD 2> /dev/null)" ] && echo 1 || echo 0
+}
+
+function AssertIsNotBareRepo
+{
+  [ "$(git rev-parse --is-bare-repository 2> /dev/null)" != 'true' ] && echo 1 || echo 0
+}
 
 function GetRefs # (refs_dir)
 {
@@ -262,7 +288,7 @@ function PrintHRule # (rule_width)
 {
   local rule_w=$1
 
-  printf "%$(($MARGIN_PAD_W))s$(head -c $rule_w < /dev/zero | tr '\0' $HRULE_CHAR)\n"
+  printf "$MARGIN_PAD$(head -c $rule_w < /dev/zero | tr '\0' $HRULE_CHAR)\n"
 }
 
 function EXIT # (err_msg)
@@ -279,36 +305,38 @@ function Init # (cli_args)
 {
   local show_dates=0
   local show_all=0
+  local show_all_synced=0
   local show_all_local=0
-  local show_all_upstream=0
   local show_all_remote=0
   local branch_a=''
   local branch_b=''
 
   # parse CLI switches
   case "$1" in
-    '-a'|'--all'     ) show_all=1                                                ;;
-    '-b'|'--branch'  ) [ "$2" ] && branch_a="$2" || branch_a=$(GetCurrentBranch) ;;
-    '-d'|'--dates'   ) show_dates=1                                              ;;
-    '-h'|'--help'    ) EXIT "$USAGE"                                             ;;
-    '-l'|'--local'   ) show_all_local=1  ; show_all_upstream=1 ;                 ;;
-    '-r'|'--remotes' ) show_all_remote=1                                         ;;
-    '-v'|'--verbose' ) show_all=1        ; show_dates=1        ;                 ;;
-    *                ) branch_a="$1"     ; branch_b="$2"       ;                 ;;
+       '-a'|'--all'     ) show_all=1                                                ;;
+       '-b'|'--branch'  ) [ "$2" ] && branch_a="$2" || branch_a=$(GetCurrentBranch) ;;
+       '-d'|'--dates'   ) show_dates=1                                              ;;
+       '-h'|'--help'    ) EXIT "$USAGE"                                             ;;
+       '-l'|'--local'   ) show_all_local=1  ; show_all_synced=1 ;                   ;;
+       '-r'|'--remotes' ) show_all_remote=1 ; show_all_synced=1 ;                   ;;
+       '-v'|'--verbose' ) show_all=1        ; show_dates=1      ;                   ;;
+       *                ) branch_a="$1"     ; branch_b="$2"     ;                   ;;
   esac
 
   # sanity checks
-  (( $(CurrentTtyW) < $MIN_TTY_W ))                                          && EXIT "tty must be wider than $MIN_TTY_W chars"
-  [ "$branch_a" ] && !(($(DoesBranchExist $branch_a)))                       && EXIT "no such branch: '$branch_a'"
-  [ "$branch_b" ] && !(($(DoesBranchExist $branch_b)))                       && EXIT "no such branch: '$branch_b'"
-  [ "$branch_a" ] && !(($(IsLocalBranch   $branch_a))) && [ -z "$branch_b" ] && EXIT "no such local branch: '$branch_a'"
-  [ "$branch_a" ] && show_all_local=1 # force "no upstream" message for non-tracking branches
+  (( $(AssertIsValidRepo  )       ))                                        || EXIT "not a git repo"
+  (( $(AssertIsNotBareRepo)       ))                                        || EXIT "bare repo"
+  (( $(AssertHasCommits   )       ))                                        || EXIT "no commits"
+  (( $(CurrentTtyW) >= $MIN_TTY_W ))                                        || EXIT "tty must be wider than $MIN_TTY_W chars"
+  [ -z "$branch_a" ] || (($(DoesBranchExist $branch_a)))                    || EXIT "no such branch: '$branch_a'"
+  [ -z "$branch_b" ] || (($(DoesBranchExist $branch_b)))                    || EXIT "no such branch: '$branch_b'"
+  [ -z "$branch_a" ] || (($(IsLocalBranch   $branch_a))) || [ "$branch_b" ] || EXIT "no such local branch: '$branch_a'"
+  [ -z "$branch_a" ] || show_all_local=1 # force "no upstream" message for non-tracking branches
 
   readonly SHOW_DATES=$show_dates
-  readonly SHOW_ALL=$show_all
-  readonly SHOW_ALL_LOCAL=$((    $show_all + $show_all_local    )) # show local branches that are not tracking any upstream
-  readonly SHOW_ALL_UPSTREAM=$(( $show_all + $show_all_upstream )) # show local branches that are synchronized with their upstream
-  readonly SHOW_ALL_REMOTE=$((   $show_all + $show_all_remote   )) # show all remote branches
+  readonly SHOW_ALL_SYNCED=$(( $show_all + $show_all_synced )) # show branches that are synchronized with their counterparts
+  readonly SHOW_ALL_LOCAL=$((  $show_all + $show_all_local  )) # show local branches that are not tracking any upstream
+  readonly SHOW_ALL_REMOTE=$(( $show_all + $show_all_remote )) # show all remote branches
   readonly FILTER_BRANCH=$branch_a
   readonly COMPARE_BRANCH=$branch_b
 }
@@ -316,36 +344,39 @@ function Init # (cli_args)
 function GenerateReports
 {
   local synchronized_msg ; local is_tracked_branch ;
-  if   [ -z "$COMPARE_BRANCH" ]
+
+  if   [ "$COMPARE_BRANCH" ]
+  then is_tracked_branch=$(IsTrackedBranch $FILTER_BRANCH $COMPARE_BRANCH)
+       (($is_tracked_branch)) && synchronized_msg="$BRANCH_SYNCED_MSG" || synchronized_msg="$UNTRACKED_SYNCHED_MSG"
+
+       # compare sync status of arbitrary branches per cli args
+       GenerateReport $FILTER_BRANCH $COMPARE_BRANCH
+       PrintReport "$FILTER_BRANCH <-> $COMPARE_BRANCH" "$synchronized_msg"
+  elif !(( $SHOW_ALL_REMOTE )) || (( $SHOW_ALL_LOCAL ))
   then [ "$FILTER_BRANCH" ] && synchronized_msg="$BRANCH_SYNCED_MSG" || synchronized_msg="$LOCALS_SYNCED_MSG"
 
-      # compare sync status of local branches to their upstreams
-      while read local upstream ; do GenerateReport $local $upstream ; done < <(GetLocalRefs) ;
-      PrintReport "local <-> upstream" "$synchronized_msg"
-  else is_tracked_branch=$(IsTrackedBranch $FILTER_BRANCH $COMPARE_BRANCH)
-      (($is_tracked_branch)) && synchronized_msg="$BRANCH_SYNCED_MSG" || synchronized_msg="$UNTRACKED_SYNCHED_MSG"
-
-      # compare sync status of arbitrary branches per cli args
-      GenerateReport $FILTER_BRANCH $COMPARE_BRANCH
-      PrintReport "$FILTER_BRANCH <-> $COMPARE_BRANCH" "$synchronized_msg"
+       # compare sync status of local branches to their upstreams
+       while read local upstream ; do GenerateReport $local $upstream ; done < <(GetLocalRefs) ;
+       PrintReport "local <-> upstream" "$synchronized_msg"
   fi
 
+  if (( $SHOW_ALL_REMOTE )) && [ -z "$FILTER_BRANCH" ]
+  then synchronized_msg="$REMOTES_SYNCED_MSG"
 
-  (($SHOW_ALL_REMOTE)) && [ -z "$FILTER_BRANCH" ] || exit
+       # compare sync status of remote branches to local branches with the same names
+       for remote_repo in $(git remote)
+       do  while read remote_branch
+           do    local local_branch=${remote_branch#$remote_repo/}
 
-  # compare sync status of remote branches to local branches with the same names
-  for remote_repo in `git remote`
-  do while read remote_branch
-    do local local_branch=${remote_branch#$remote_repo/}
+                 GenerateReport $local_branch $remote_branch
+           done < <(GetRemoteRefs $remote_repo)
 
-        GenerateReport $local_branch $remote_branch
-    done < <(GetRemoteRefs $remote_repo)
-
-    PrintReport "local <-> $remote_repo" "$REMOTES_SYNCED_MSG"
-  done
+           PrintReport "local <-> $remote_repo" "$synchronized_msg"
+       done
+  fi
 }
 
-function GenerateReport # (local_branch_name remote_branch_name)
+function GenerateReport # (base_branch compare_branch)
 {
   local base_branch=$1
   local compare_branch=$2
@@ -356,13 +387,13 @@ function GenerateReport # (local_branch_name remote_branch_name)
   local local_color ; local behind_color ; local ahead_color ; local remote_color ;
 
   # filter heads
-  [ "$base_branch" == 'HEAD' ] && return
+  [ "$base_branch" != 'HEAD' ] || return
 
   # filter branches per CLI arg
-  [ "$FILTER_BRANCH" -a "$base_branch" != "$FILTER_BRANCH" ] && return
+  [ -z "$FILTER_BRANCH" -o "$base_branch" == "$FILTER_BRANCH" ] || return
 
   # parse local<->remote or arbitrary branches sync status
-  if (($does_base_branch_exist)) && (($does_compare_branch_exist))
+  if   (($does_base_branch_exist)) && (($does_compare_branch_exist))
   then local status=$(GetStatus $base_branch $compare_branch) ; (($?)) && return ;
 
        local n_behind=$(echo $status | tr " " "\n" | grep -c '^>')
@@ -372,16 +403,16 @@ function GenerateReport # (local_branch_name remote_branch_name)
        WereAnyCompared=1
 
        # filter branches by status
-       (($SHOW_ALL_UPSTREAM)) || (($n_divergances)) || return
+       (($SHOW_ALL_SYNCED)) || (($n_divergances)) || return
 
        # set data for branches with remote counterparts or arbitrary branches
        (($is_tracked_branch)) && color=$CTRACKING || color=$CDEFAULT
        local_color=$color
-       if (($n_behind))
+       if   (($n_behind))
        then behind_msg="(behind$JOIN_CHAR$n_behind)" ; behind_color=$CBEHIND ;
        else behind_msg="(even)"                      ; behind_color=$CEVEN   ;
        fi
-       if (($n_ahead))
+       if   (($n_ahead))
        then ahead_msg="(ahead$JOIN_CHAR$n_ahead)"    ; ahead_color=$CAHEAD   ;
        else ahead_msg="(even)"                       ; ahead_color=$CEVEN    ;
        fi
@@ -400,8 +431,10 @@ function GenerateReport # (local_branch_name remote_branch_name)
        remote_color=$CDEFAULT
   else return
   fi
-  local_msg="$( AppendHeadDate $base_branch   )"
-  remote_msg="$(AppendHeadDate $compare_branch)"
+  local_msg="$( AppendHeadDate $base_branch         )"
+  behind_msg=$( echo $behind_msg | sed "$TRIM_REGEX")
+  ahead_msg=$(  echo $behind_msg | sed "$TRIM_REGEX")
+  remote_msg="$(AppendHeadDate $compare_branch      )"
 
   # populate lists
   LocalMsgs=(    ${LocalMsgs[@]}    "$local_msg"    )
@@ -425,12 +458,11 @@ function PrintReport # (table_header_line synchronized_msg)
   local table_header_line=$1
   local synchronized_msg=$2
   local available_w=$(( $(CurrentTtyW) - $AheadW - $BehindW - $ALL_PADDING_W ))
-  local n_comparissons=${#LocalMsgs[@]}
+  local n_results=${#LocalMsgs[@]}
   local all_in_sync
   (( $WereAnyCompared )) && !(( $WereAnyDivergances )) && all_in_sync=1 || all_in_sync=0
 
-  (( $available_w    <  0 ))                            && ERR "((available_w<0))"
-  (( $n_comparissons == 0 )) && (( $all_in_sync == 0 )) && ERR "((n_comparissons+all_in_sync==0))"
+  (( $n_results == 0 )) && (( $all_in_sync == 0 )) && EXIT "nothing to compare"
 
   # truncate column widths to fit
   while (( $LocalW + $RemoteW > $available_w ))
@@ -439,18 +471,18 @@ function PrintReport # (table_header_line synchronized_msg)
   done
 
   # pretty print results
-  printf "\n  $table_header_line\n"
-  if (( $n_comparissons ))
+  printf "\n$MARGIN_PAD$table_header_line\n"
+  if   (( $n_results ))
   then local rule_w=$(( $LocalW + $BehindW + $AheadW + $RemoteW + $INNER_PADDING_W ))
        PrintHRule $rule_w
-       for (( result_n = 0 ; result_n < $n_comparissons ; result_n++ ))
-       do PrintReportLine
+       for (( result_n = 0 ; result_n < $n_results ; result_n++ ))
+       do  PrintReportLine
        done
        PrintHRule $rule_w
   fi
 
   # print synchronized message if all compared upstreams had no divergance
-  if (( $all_in_sync ))
+  if   (( $all_in_sync ))
   then l_border="$DELIM " r_border=" $DELIM"
        borders_pad_w=$(( ${#l_border} + ${#r_border} ))
        wrap_w=$(( $(CurrentTtyW) - $MARGINS_PAD_W - $borders_pad_w ))
@@ -466,7 +498,7 @@ function PrintReport # (table_header_line synchronized_msg)
        for line in $synchronized_msg
        do  line=${line/%$JOIN_CHAR/}
            pad_w=$(( $rule_w - ${#line} - $MARGINS_PAD_W ))
-           line_fmt="%$(( $MARGIN_PAD_W ))s$l_border$CEVEN$line$CEND%$(( $pad_w ))s$r_border"
+           line_fmt="$MARGIN_PAD$l_border$CEVEN$line$CEND%$(( $pad_w ))s$r_border"
            printf "$line_fmt\n" | sed "$JOIN_REGEX"
        done
        PrintHRule $rule_w
@@ -478,10 +510,10 @@ function PrintReport # (table_header_line synchronized_msg)
 function PrintReportLine
 {
   # fetch data
-  local local_msg=$( echo ${LocalMsgs[$result_n]}  | sed "$JOIN_REGEX")
-  local behind_msg=$(echo ${BehindMsgs[$result_n]} | sed "$JOIN_REGEX")
-  local ahead_msg=$( echo ${AheadMsgs[$result_n]}  | sed "$JOIN_REGEX")
-  local remote_msg=$(echo ${RemoteMsgs[$result_n]} | sed "$JOIN_REGEX")
+  local local_msg=$( echo ${LocalMsgs[ $result_n]}         | sed "$JOIN_REGEX")
+  local behind_msg=$(echo ${BehindMsgs[$result_n]:$trim_w} | sed "$JOIN_REGEX")
+  local ahead_msg=$( echo ${AheadMsgs[ $result_n]:$trim_w} | sed "$JOIN_REGEX")
+  local remote_msg=$(echo ${RemoteMsgs[$result_n]}         | sed "$JOIN_REGEX")
   local end_msg ; local star ;
   local_msg="${local_msg:0:$LocalW}"
   remote_msg="${remote_msg:0:$RemoteW}"
@@ -498,7 +530,7 @@ function PrintReportLine
   local end_offset=$((    $RemoteW - ${#remote_msg} ))
 
   # build output messages and display
-  if (( $(IsCurrentBranch $local_msg) )) ; then star=$STAR ; else star=" " ; fi ;
+  (( $(IsCurrentBranch $local_msg) )) && star=$STAR || star=" "
   local_msg="%$((  $local_offset  ))s$star$(echo -e $DELIM $local_color$local_msg$CEND  )"
   behind_msg="%$(( $behind_offset ))s $(    echo -e $DELIM $behind_color$behind_msg$CEND)"
   ahead_msg="%$((  $ahead_offset  ))s $(    echo -e $DELIM $ahead_color$ahead_msg$CEND  )"
